name: "Build & Deploy"
description: "Build and deploy iOS application"
inputs:
  certificate-path:
    description: "signing certificate p12 file"
    required: true
  provisioning-profile-path:
    description: "provisioning profile file"
    required: true
  itunes-connect-username:
    description: "Itunes connect username"
    required: true
  itunes-connect-password:
    description: "Itunes connect password"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "dist/index.js"
